// This file is automatically generated by the build process.
// It is not intended for manual editing.
//
// It scans for all files in the extensions directory and exports them.
// This allows for a CI/CD-friendly way to add new extensions.

const modules = import.meta.glob('./**/*.js', { eager: true });

const cards = [];
const routes = [];

for (const path in modules) {
    const mod = modules[path];
    if (mod.card) {
        cards.push(mod.card);
    }
    if (mod.route) {
        routes.push(mod.route);
    }
}

export { cards, routes };