name: Documentation Issue
description: Report an issue or suggest an improvement for the documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve Gofannon's documentation! Good documentation helps everyone.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of documentation issue is this?
      options:
        - Incorrect/outdated information
        - Missing documentation
        - Unclear explanation
        - Typo/grammar
        - Code example issue
        - Suggestion for improvement
        - Other
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: Which file or page has the issue? (e.g., docs/api.md or a URL)
      placeholder: docs/developers-quickstart.md
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue in detail.
      placeholder: |
        What is wrong or missing? Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: If you have a suggestion for how to fix or improve the documentation, please describe it here.
      placeholder: |
        What should the documentation say instead?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute this fix?
      options:
        - label: I would be willing to submit a PR to fix this issue

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/the-ai-alliance/gofannon/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
